### ISSUE TITLE
Docker: for development

### ISSUE THREAD

**Issue by davidteren** [davidteren/sensible_rails_starter#58]

**Comment by hexagile** [comment]
I believe this worked really well @ RCRDSHP (just `docker-compose up dev` and you didn't have to worry about all the dependencies and shit). Looking forward to this (I *might* be able to find the time to set it up, but I wouldn't count on that just yet).

I'd prioritize this b/c it's super easy to get started with the project...

**Comment by davidteren** [comment]
Addressed in this [Add docker for development by davidteren · Pull Request #73 · davidteren/sensible\_rails\_starter (github.com)](https://github.com/davidteren/sensible_rails_starter/pull/73)  
  
Thanks to @palkan's post [Ruby on Whales: Dockerizing Ruby and Rails development—Martian Chronicles, Evil Martians’ team blog](https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development)
